[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tutorial-project"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["mainsequence"]

[tool.setuptools.packages.find]
where = ["src"]

